package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCrmOwnerRecord<M extends BaseCrmOwnerRecord<M>> extends Model<M> implements IBean {

	public void setRecordId(java.lang.Integer recordId) {
		set("record_id", recordId);
	}
	
	public java.lang.Integer getRecordId() {
		return getInt("record_id");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setPreOwnerUserId(java.lang.Integer preOwnerUserId) {
		set("pre_owner_user_id", preOwnerUserId);
	}
	
	public java.lang.Integer getPreOwnerUserId() {
		return getInt("pre_owner_user_id");
	}

	public void setPostOwnerUserId(java.lang.Integer postOwnerUserId) {
		set("post_owner_user_id", postOwnerUserId);
	}
	
	public java.lang.Integer getPostOwnerUserId() {
		return getInt("post_owner_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
