package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminScene<M extends BaseAdminScene<M>> extends Model<M> implements IBean {

	public void setSceneId(java.lang.Integer sceneId) {
		set("scene_id", sceneId);
	}
	
	public java.lang.Integer getSceneId() {
		return getInt("scene_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}
	
	public java.lang.String getData() {
		return getStr("data");
	}

	public void setIsHide(java.lang.Integer isHide) {
		set("is_hide", isHide);
	}
	
	public java.lang.Integer getIsHide() {
		return getInt("is_hide");
	}

	public void setIsSystem(java.lang.Integer isSystem) {
		set("is_system", isSystem);
	}
	
	public java.lang.Integer getIsSystem() {
		return getInt("is_system");
	}

	public void setBydata(java.lang.String bydata) {
		set("bydata", bydata);
	}
	
	public java.lang.String getBydata() {
		return getStr("bydata");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
