package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminFile<M extends BaseAdminFile<M>> extends Model<M> implements IBean {

	public void setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.Integer getFileId() {
		return getInt("file_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSize(java.lang.Integer size) {
		set("size", size);
	}
	
	public java.lang.Integer getSize() {
		return getInt("size");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}
	
	public java.lang.String getFilePath() {
		return getStr("file_path");
	}

	public void setFileType(java.lang.String fileType) {
		set("file_type", fileType);
	}
	
	public java.lang.String getFileType() {
		return getStr("file_type");
	}

	public void setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
	}
	
	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

}
