package com.erpsnow.erp;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdminFieldSort<M extends BaseAdminFieldSort<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLabel(java.lang.Integer label) {
		set("label", label);
	}
	
	public java.lang.Integer getLabel() {
		return getInt("label");
	}

	public void setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
	}
	
	public java.lang.String getFieldName() {
		return getStr("field_name");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setIsHide(java.lang.Integer isHide) {
		set("is_hide", isHide);
	}
	
	public java.lang.Integer getIsHide() {
		return getInt("is_hide");
	}

	public void setFieldId(java.lang.Integer fieldId) {
		set("field_id", fieldId);
	}
	
	public java.lang.Integer getFieldId() {
		return getInt("field_id");
	}

}
