package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminConfig extends BaseAdminConfig<AdminConfig> {
	public static final AdminConfig dao = new AdminConfig().dao();
}
