package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminScene;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminScene extends BaseAdminScene<AdminScene> {
	public static final AdminScene dao = new AdminScene().dao();
}
