package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminFieldv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldv extends BaseAdminFieldv<AdminFieldv> {
	public static final AdminFieldv dao = new AdminFieldv().dao();
}
