package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminExamineRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineRecord extends BaseAdminExamineRecord<AdminExamineRecord> {
	public static final AdminExamineRecord dao = new AdminExamineRecord().dao();
}
