package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRoleMenu extends BaseAdminRoleMenu<AdminRoleMenu> {
	public static final AdminRoleMenu dao = new AdminRoleMenu().dao();
}
