package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFile extends BaseAdminFile<AdminFile> {
	public static final AdminFile dao = new AdminFile().dao();
}
