package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminExamineLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineLog extends BaseAdminExamineLog<AdminExamineLog> {
	public static final AdminExamineLog dao = new AdminExamineLog().dao();
}
