package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminFieldSort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldSort extends BaseAdminFieldSort<AdminFieldSort> {
	public static final AdminFieldSort dao = new AdminFieldSort().dao();
}
