package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminDept extends BaseAdminDept<AdminDept> {
	public static final AdminDept dao = new AdminDept().dao();
}
