package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminExamine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamine extends BaseAdminExamine<AdminExamine> {
	public static final AdminExamine dao = new AdminExamine().dao();
}
