package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRecord extends BaseAdminRecord<AdminRecord> {
	public static final AdminRecord dao = new AdminRecord().dao();
}
