package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUser extends BaseAdminUser<AdminUser> {
	public static final AdminUser dao = new AdminUser().dao();
}
