package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminSceneDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminSceneDefault extends BaseAdminSceneDefault<AdminSceneDefault> {
	public static final AdminSceneDefault dao = new AdminSceneDefault().dao();
}
