package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminExamineStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExamineStep extends BaseAdminExamineStep<AdminExamineStep> {
	public static final AdminExamineStep dao = new AdminExamineStep().dao();
}
