package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUserRole extends BaseAdminUserRole<AdminUserRole> {
	public static final AdminUserRole dao = new AdminUserRole().dao();
}
