package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminMenu extends BaseAdminMenu<AdminMenu> {
	public static final AdminMenu dao = new AdminMenu().dao();
}
