package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminField extends BaseAdminField<AdminField> {
	public static final AdminField dao = new AdminField().dao();
}
