package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseAdminFieldStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminFieldStyle extends BaseAdminFieldStyle<AdminFieldStyle> {
	public static final AdminFieldStyle dao = new AdminFieldStyle().dao();
}
