package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmActionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmActionRecord extends BaseCrmActionRecord<CrmActionRecord> {
	public static final CrmActionRecord dao = new CrmActionRecord().dao();
}
