package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmAchievement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmAchievement extends BaseCrmAchievement<CrmAchievement> {
	public static final CrmAchievement dao = new CrmAchievement().dao();
}
