package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmBusinessStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessStatus extends BaseCrmBusinessStatus<CrmBusinessStatus> {
	public static final CrmBusinessStatus dao = new CrmBusinessStatus().dao();
}
