package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmBusinessType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessType extends BaseCrmBusinessType<CrmBusinessType> {
	public static final CrmBusinessType dao = new CrmBusinessType().dao();
}
