package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmBusinessProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessProduct extends BaseCrmBusinessProduct<CrmBusinessProduct> {
	public static final CrmBusinessProduct dao = new CrmBusinessProduct().dao();
}
