package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusiness extends BaseCrmBusiness<CrmBusiness> {
	public static final CrmBusiness dao = new CrmBusiness().dao();
}
