package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmBusinessChange;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessChange extends BaseCrmBusinessChange<CrmBusinessChange> {
	public static final CrmBusinessChange dao = new CrmBusinessChange().dao();
}
