package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmCustomerSettinguser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerSettinguser extends BaseCrmCustomerSettinguser<CrmCustomerSettinguser> {
	public static final CrmCustomerSettinguser dao = new CrmCustomerSettinguser().dao();
}
