package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmContractProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContractProduct extends BaseCrmContractProduct<CrmContractProduct> {
	public static final CrmContractProduct dao = new CrmContractProduct().dao();
}
