package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmCustomerStats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerStats extends BaseCrmCustomerStats<CrmCustomerStats> {
	public static final CrmCustomerStats dao = new CrmCustomerStats().dao();
}
