package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomer extends BaseCrmCustomer<CrmCustomer> {
	public static final CrmCustomer dao = new CrmCustomer().dao();
}
