package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContacts extends BaseCrmContacts<CrmContacts> {
	public static final CrmContacts dao = new CrmContacts().dao();
}
