package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmContactsBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContactsBusiness extends BaseCrmContactsBusiness<CrmContactsBusiness> {
	public static final CrmContactsBusiness dao = new CrmContactsBusiness().dao();
}
