package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmContract extends BaseCrmContract<CrmContract> {
	public static final CrmContract dao = new CrmContract().dao();
}
