package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmCustomerSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerSetting extends BaseCrmCustomerSetting<CrmCustomerSetting> {
	public static final CrmCustomerSetting dao = new CrmCustomerSetting().dao();
}
