package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmLeads;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmLeads extends BaseCrmLeads<CrmLeads> {
	public static final CrmLeads dao = new CrmLeads().dao();
}
