package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmOwnerRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmOwnerRecord extends BaseCrmOwnerRecord<CrmOwnerRecord> {
	public static final CrmOwnerRecord dao = new CrmOwnerRecord().dao();
}
