package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmProduct extends BaseCrmProduct<CrmProduct> {
	public static final CrmProduct dao = new CrmProduct().dao();
}
