package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmProductCategory extends BaseCrmProductCategory<CrmProductCategory> {
	public static final CrmProductCategory dao = new CrmProductCategory().dao();
}
