package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmReceivablesPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivablesPlan extends BaseCrmReceivablesPlan<CrmReceivablesPlan> {
	public static final CrmReceivablesPlan dao = new CrmReceivablesPlan().dao();
}
