package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseCrmReceivables;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivables extends BaseCrmReceivables<CrmReceivables> {
	public static final CrmReceivables dao = new CrmReceivables().dao();
}
