package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaActionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaActionRecord extends BaseOaActionRecord<OaActionRecord> {
	public static final OaActionRecord dao = new OaActionRecord().dao();
}
