package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaAnnouncement extends BaseOaAnnouncement<OaAnnouncement> {
	public static final OaAnnouncement dao = new OaAnnouncement().dao();
}
