package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaEventNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEventNotice extends BaseOaEventNotice<OaEventNotice> {
	public static final OaEventNotice dao = new OaEventNotice().dao();
}
