package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaEventRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEventRelation extends BaseOaEventRelation<OaEventRelation> {
	public static final OaEventRelation dao = new OaEventRelation().dao();
}
