package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaEvent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaEvent extends BaseOaEvent<OaEvent> {
	public static final OaEvent dao = new OaEvent().dao();
}
