package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineRelation extends BaseOaExamineRelation<OaExamineRelation> {
	public static final OaExamineRelation dao = new OaExamineRelation().dao();
}
