package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineTravel extends BaseOaExamineTravel<OaExamineTravel> {
	public static final OaExamineTravel dao = new OaExamineTravel().dao();
}
