package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamine extends BaseOaExamine<OaExamine> {
	public static final OaExamine dao = new OaExamine().dao();
}
