package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineRecord extends BaseOaExamineRecord<OaExamineRecord> {
	public static final OaExamineRecord dao = new OaExamineRecord().dao();
}
