package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineStep extends BaseOaExamineStep<OaExamineStep> {
	public static final OaExamineStep dao = new OaExamineStep().dao();
}
