package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineLog extends BaseOaExamineLog<OaExamineLog> {
	public static final OaExamineLog dao = new OaExamineLog().dao();
}
