package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaExamineCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaExamineCategory extends BaseOaExamineCategory<OaExamineCategory> {
	public static final OaExamineCategory dao = new OaExamineCategory().dao();
}
