package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaLogRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLogRelation extends BaseOaLogRelation<OaLogRelation> {
	public static final OaLogRelation dao = new OaLogRelation().dao();
}
