package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseOaLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaLog extends BaseOaLog<OaLog> {
	public static final OaLog dao = new OaLog().dao();
}
