package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();
}
