package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseTaskRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskRelation extends BaseTaskRelation<TaskRelation> {
	public static final TaskRelation dao = new TaskRelation().dao();
}
