package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseTaskComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskComment extends BaseTaskComment<TaskComment> {
	public static final TaskComment dao = new TaskComment().dao();
}
