package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Work extends BaseWork<Work> {
	public static final Work dao = new Work().dao();
}
