package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseWorkTaskLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskLabel extends BaseWorkTaskLabel<WorkTaskLabel> {
	public static final WorkTaskLabel dao = new WorkTaskLabel().dao();
}
