package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseWorkTaskClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskClass extends BaseWorkTaskClass<WorkTaskClass> {
	public static final WorkTaskClass dao = new WorkTaskClass().dao();
}
