package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseWorkTaskLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkTaskLog extends BaseWorkTaskLog<WorkTaskLog> {
	public static final WorkTaskLog dao = new WorkTaskLog().dao();
}
