package com.kakarote.crm9.test;

import com.erpsnow.erp.BaseWorkUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkUser extends BaseWorkUser<WorkUser> {
	public static final WorkUser dao = new WorkUser().dao();
}
